#!/bin/sh
cd /var/www/html
cp .env.example .env
chmod -R 777 storage
composer install


set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"